export const products = [
  {
    "id-producto": 1,
    "discount": 14,
    "URL-image": "c55.webp",
    "patrocinado": 1,
    "envio_gratis": 1,
    "nombre1": "Realme C55 8/256GB",
    "nombre2": "Rainy Night Libre",
    "marca": "Realme",
    "precio": 199,
    "PVPR": 231,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 178,
    "patrocinado": 1,
    "recibelo_manyana": 0,
    "envio_gratis": 1,
    "seller": "PcComponentes",
    "stock": 940
  },
  {
    "id-producto": 2,
    "discount": 43,
    "URL-image": "Realme Narzo 50i Prime.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "Realme Narzo 50i Prime",
    "nombre2": "3/32/GB",
    "marca": "Realme",
    "precio": 79,
    "PVPR": 139,
    "moneda": "€",
    "nr_stars": 4,
    "nr_reviews": 84,
    "patrocinado": 0,
    "recibelo_manyana": 0,
    "envio_gratis": 1,
    "seller": "PcComponentes",
    "stock": 10
  },
  {
    "id-producto": 3,
    "discount": 34,
    "URL-image": "Motorola Moto G23.webp",
    "patrocinado": 1,
    "envio_gratis": 1,
    "nombre1": "Motorola Moto G23",
    "nombre2": "8/128GB Gris",
    "marca": "Motorola",
    "precio": 149,
    "PVPR": 229,
    "moneda": "€",
    "nr_stars": 4,
    "nr_reviews": 57,
    "patrocinado": 1,
    "recibelo_manyana": 0,
    "envio_gratis": 1,
    "seller": "PcComponentes",
    "stock": 310
  },
  {
    "id-producto": 4,
    "discount": 6,
    "URL-image": "Samsung Galaxy A54 5G.webp",
    "patrocinado": 1,
    "envio_gratis": 1,
    "nombre1": "Samsung Galaxy A54 5G",
    "nombre2": "8/128GB Violeta Libre",
    "marca": "Samsung",
    "precio": 469,
    "PVPR": 499,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 5,
    "patrocinado": 1,
    "recibelo_manyana": 0,
    "envio_gratis": 1,
    "seller": "PcComponentes",
    "stock": 150
  },
  {
    "id-producto": 5,
    "discount": 0,
    "URL-image": "OPPO Reno 10 5G.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "OPPO Reno 10 5G",
    "nombre2": "8/256GB Azul",
    "marca": "Oppo",
    "precio": 479,
    "PVPR": 479,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 3,
    "patrocinado": 0,
    "recibelo_manyana": 0,
    "envio_gratis": 1,
    "seller": "PcComponentes",
    "stock": 170
  },
  {
    "id-producto": 6,
    "discount": 9,
    "URL-image": "OPPO A98 5G.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "OPPO A98 5G ",
    "nombre2": "8/256GB Negro Libre",
    "marca": "Oppo",
    "precio": 348,
    "PVPR": 385,
    "moneda": "€",
    "nr_stars": 3,
    "nr_reviews": 7,
    "patrocinado": 0,
    "recibelo_manyana": 0,
    "envio_gratis": 0,
    "seller": "PcComponentes",
    "stock": 140
  },
  {
    "id-producto": 7,
    "discount": 33,
    "URL-image": "Motorola Moto E13.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "Motorola Moto E13",
    "nombre2": "2/64GB Negro",
    "marca": "Motorola",
    "precio": 79,
    "PVPR": 119,
    "moneda": "€",
    "nr_stars": 4,
    "nr_reviews": 7,
    "patrocinado": 0,
    "recibelo_manyana": 1,
    "envio_gratis": 0,
    "seller": "PcComponentes",
    "stock": 210
  },
  {
    "id-producto": 8,
    "discount": 42,
    "URL-image": "Samsung Galaxy Z Fold4.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "Samsung Galaxy Z Fold4",
    "nombre2": "512GB Verde libre+Carg.25W",
    "marca": "Samsung",
    "precio": 1098,
    "PVPR": 1919,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 6,
    "patrocinado": 0,
    "recibelo_manyana": 1,
    "envio_gratis": 0,
    "seller": "PcComponentes",
    "stock": 250
  },
  {
    "id-producto": 9,
    "discount": 9,
    "URL-image": "Apple iPhone 13 128GB.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "Apple iPhone 13 128GB",
    "nombre2": "Medianoche Libre",
    "marca": "Apple",
    "precio": 825,
    "PVPR": 999,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 72,
    "patrocinado": 0,
    "recibelo_manyana": 1,
    "envio_gratis": 0,
    "seller": "PcComponentes",
    "stock": 260
  }
  ,
  {
    "id-producto": 10,
    "discount": 12,
    "URL-image": "Apple iPhone 14 128GB.webp",
    "patrocinado": 0,
    "envio_gratis": 1,
    "nombre1": "Apple iPhone 14 128GB",
    "nombre2": "Blanco Estrella Libre",
    "marca": "Apple",
    "precio": 879,
    "PVPR": 1000,
    "moneda": "€",
    "nr_stars": 5,
    "nr_reviews": 67,
    "patrocinado": 0,
    "recibelo_manyana": 1,
    "envio_gratis": 0,
    "seller": "PcComponentes",
    "stock": 200
  }
];



